---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-switcher
  annotations:
    render.crossplane.io/runtime: Development
# spec:
  # package: ghcr.io/kndpio/kndp/function-switcher:0.1.0
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-patch-and-transform
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.1.4